# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'bfaa6bc6-9775-4d15-bf70-5bba69811803'
    pipeline: '10'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.DefaultWorkingDirectory)/yuzu-definition-import'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.DefaultWorkingDirectory)
    ArtifactName: 'drop'
  displayName: 'Publish artifacts'
